<?php declare(strict_types=1);

namespace AutoDoc\TypeScript;

class GeneratedTypeScriptFile
{
    public function __construct(
        public readonly string $filePath,
    ) {}

    public function write(string $body): void
    {
        file_put_contents(
            $this->filePath,
            '/**' . "\n"
                . ' * This file is auto-generated by PHP AutoDoc.' . "\n"
                . ' * Documentation: https://phpautodoc.com/docs/typescript' . "\n"
                . ' */' . "\n\n"
                . $body,
        );
    }
}
