<?php declare(strict_types=1);

namespace AutoDoc\Tests;

use AutoDoc\Route;
use AutoDoc\Tests\TestProject\RouteMutationTrackingLoader;
use AutoDoc\Tests\Traits\LoadsConfig;
use AutoDoc\TypeScript\RoutesExporter;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class RoutesExporterTest extends TestCase
{
    use LoadsConfig;

    private string $temporaryDirectory;
    private string $generatedFile;

    protected function setUp(): void
    {
        $this->temporaryDirectory = sys_get_temp_dir() . '/autodoc-routes-' . uniqid();
        $this->generatedFile = $this->temporaryDirectory . '/routes.ts';
        mkdir($this->temporaryDirectory);
    }

    protected function tearDown(): void
    {
        RouteMutationTrackingLoader::$route = null;

        if (file_exists($this->generatedFile)) {
            unlink($this->generatedFile);
        }

        if (is_dir($this->temporaryDirectory)) {
            rmdir($this->temporaryDirectory);
        }
    }

    #[Test]
    public function itExportsRequestAndResponseRouteMapsToAGeneratedFile(): void
    {
        $config = self::loadConfig();

        if (! isset($config->data['typescript']['export_http_requests_and_responses']['@/requests-and-responses.ts'])) {
            $this->fail('Expected the route-export test configuration to exist.');
        }

        $options = $config->data['typescript']['export_http_requests_and_responses']['@/requests-and-responses.ts'];
        $config->data['typescript']['path_prefixes'] = fn () => ['@' => $this->temporaryDirectory];
        $config->data['typescript']['export_http_requests_and_responses'] = [
            '@/routes.ts' => $options,
        ];

        $result = (new RoutesExporter($config, '@/routes.ts', $options))->export();

        $this->assertSame([
            'filePath' => $this->generatedFile,
            'exportedRequests' => 2,
            'exportedResponses' => 2,
        ], $result);

        $contents = file_get_contents($this->generatedFile);
        $this->assertIsString($contents);
        $this->assertStringStartsWith("/**\n * This file is auto-generated by PHP AutoDoc.", $contents);
        $this->assertStringContainsString("export type Requests = {\n    '/api/test/requestparams/headers-and-request-body'", $contents);
        $this->assertStringContainsString("export type Responses = {\n    '/api/test/arrayoperations/array-values-on-assoc-array'", $contents);
    }

    #[Test]
    public function itDoesNotMutateRoutesOwnedByTheRouteLoader(): void
    {
        $config = self::loadConfig();
        $config->data['route_loader'] = RouteMutationTrackingLoader::class;
        $config->data['typescript']['path_prefixes'] = fn () => ['@' => $this->temporaryDirectory];
        $options = [
            'routes' => ['original/path'],
            'request_methods' => ['post'],
        ];
        $config->data['typescript']['export_http_requests_and_responses'] = [
            '@/routes.ts' => $options,
        ];

        $route = new Route(
            uri: 'original/path',
            method: 'POST',
            closure: static fn (): array => ['ok' => true],
        );
        RouteMutationTrackingLoader::$route = $route;

        new RoutesExporter($config, '@/routes.ts', $options)->export();

        $this->assertSame('original/path', $route->uri);
        $this->assertSame('POST', $route->method);
    }
}
