<?php declare(strict_types=1);

namespace AutoDoc\Tests;

use AutoDoc\Analyzer\Scope;
use AutoDoc\Tests\Traits\LoadsConfig;
use AutoDoc\TypeScript\TypeScriptFile;
use AutoDoc\TypeScript\TypeScriptGenerator;
use Exception;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class TypeScriptSchemaTest extends TestCase
{
    use LoadsConfig;

    private static Scope $scope;
    private static TypeScriptGenerator $generator;

    public static function setUpBeforeClass(): void
    {
        self::$scope = new Scope(self::loadConfig());
        self::$generator = new TypeScriptGenerator(self::$scope->config);
    }


    public static function tearDownAfterClass(): void
    {
        self::$generator->overwriteGeneratedFiles();

        $generatedFileName = __DIR__ . '/typescript/types.ts';

        self::assertFileExists($generatedFileName);

        $fileContents = file_get_contents($generatedFileName);

        self::assertIsString($fileContents);

        $fileContents = str_replace("\r\n", "\n", $fileContents);

        self::assertEquals($fileContents, str_replace("\r\n", "\n", <<<EOF
        /**
         * This file is auto-generated by PHP AutoDoc.
         * Documentation: https://phpautodoc.com/docs/typescript
         */

        export type SimpleClass = {
            n: number|null
        }

        export type ExampleObject = {
            summary: string
            description: string
            value: unknown|null
            externalValue: string|null
        }

        export type AnotherName = {
            n: number|null
            yo: string
            state: 1|2
        }

        export type Route32Response = {
            15: Record<string, 4.21|true|'Big'|'Small'>
        }

        export type Route36Response = Array<Array<1|2|3|'a'|'b'|'c'>>

        export type SomeType = {
            a: number
            b: string
        }

        export enum RocketCategory {
            Big = 'Big',
            Small = 'Small',
        }

        export type Route14Request = {
            data: Record<string, {
                id: number
                name?: string
            }>
            token: string
        }
        EOF));
    }


    private function assertTypeScriptGeneratedCorrectly(string $input, string $expected): void
    {
        $tsFile = new TypeScriptFile(null, self::$generator);

        $this->assertIsCallable(self::$scope->config->data['typescript']['path_prefixes'] ?? null);

        foreach (self::$scope->config->data['typescript']['path_prefixes']() as $prefix => $path) {
            if (! is_dir($path)) {
                mkdir($path);
            }

            $this->assertDirectoryExists($path);
        }

        $tsFile->lines = explode("\n", str_replace("\r\n", "\n", $input));

        $tsFile->processAutodocTags(self::$scope);

        $result = implode("\n", $tsFile->lines);
        $expected = str_replace("\r\n", "\n", $expected);

        $this->assertEquals($expected, $result);
    }


    #[Test]
    public function simpleBuiltInClass(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc ReflectionEnum */
            ',
            expected: '
            /** @autodoc ReflectionEnum */
            type ReflectionEnum = {
                name: string
            }
            ',
        );
    }

    #[Test]
    public function genericClassNoIndent(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: ''
                . '/*' . "\n"
                . '@autodoc AutoDoc\Tests\TestProject\Entities\GenericClass' . "\n"
                . '*/' . "\n",
            expected: ''
                . '/*' . "\n"
                . '@autodoc AutoDoc\Tests\TestProject\Entities\GenericClass' . "\n"
                . '*/' . "\n"
                . 'type GenericClass = {' . "\n"
                . '    data: unknown' . "\n"
                . '}' . "\n",
        );
    }

    #[Test]
    public function enumDeclarationUpdate(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
                /*@autodoc AutoDoc\Tests\TestProject\Entities\RocketCategory
            */
            export enum RocketCategoryEnum {}
            export type RocketName = string
            ',
            expected: "
                /*@autodoc AutoDoc\Tests\TestProject\Entities\RocketCategory
            */
            export enum RocketCategoryEnum {
                Big = 'Big',
                Small = 'Small',
            }
            export type RocketName = string
            ",
        );
    }

    #[Test]
    public function typeDeclarationUpdate(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass */
            type SimpleClass = {
            }
            ',
            expected: '
            /** @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass */
            type SimpleClass = {
                n: number|null
            }
            ',
        );
    }

    #[Test]
    public function enumUpdateAndThreeClasses(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            yoo

            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\StateEnum
             */
            enum StateEnum {
                One = 1,
            }

            /*
            yoyo
            @autodoc   AutoDoc\Route

            */

            text ...

            /** @autodoc AutoDoc\OpenApi\InfoObject */
            interface InfoObject

            /** @autodoc ReflectionClass */',
            expected: '
            yoo

            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\StateEnum
             */
            enum StateEnum {
                One = 1,
                Two = 2,
            }

            /*
            yoyo
            @autodoc   AutoDoc\Route

            */
            type Route = {
                uri: string
                method: string
                className: string|null
                classMethod: string|null
                closure: {}|null
                meta: unknown[]
                responses: Array<{
                    status?: number
                    contentType?: string
                    body?: {
                        description: string|null
                        examples: unknown|null
                        required: boolean
                        deprecated: boolean
                        example: Record<string, unknown>|string|null
                        isEnum: boolean
                    }
                }>
            }

            text ...

            /** @autodoc AutoDoc\OpenApi\InfoObject */
            interface InfoObject {
                title: string
                version: string
                description: string
            }

            /** @autodoc ReflectionClass */
            type ReflectionClass = {
                name: string
            }',
        );
    }

    #[Test]
    public function closureResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/closure1 */
            ',
            expected: '
            /** @autodoc GET /api/test/closure1 */
            type Closure1Response = Array<{
                test: boolean
            }>
            ',
        );
    }

    #[Test]
    public function closureWithScalarResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/closure3 200 */
            ',
            expected: '
            /** @autodoc GET /api/test/closure3 200 */
            type Closure3Response = number|null
            ',
        );
    }

    #[Test]
    public function controllerMethodWithArrayShapeResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc get /api/test/route9 */
            ',
            expected: '
            /** @autodoc get /api/test/route9 */
            type Route9Response = {
                text: string
                encoded: string
                count: number
                enum: 1|2
            }
            ',
        );
    }

    #[Test]
    public function controllerMethodWithExistingNumberType(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route6 */
            type TypeWithExistingName = number
            ',
            expected: "
            /** @autodoc GET /api/test/route6 */
            type TypeWithExistingName = {
                data: Array<'abc'|123>
            }
            ",
        );
    }

    #[Test]
    public function controllerMethodWithObjectHavingArrayOfObjects(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/closure4 */
            ',
            expected: '
            /** @autodoc GET /api/test/closure4 */
            type Closure4Response = {
                list: Array<{
                    id: number
                    name: string
                }>
            }
            ',
        );
    }

    #[Test]
    public function controllerMethodWithTupleResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route10 */
            interface TestResponseInterface {
                {{{}}}
            }
            ',
            expected: '
            /** @autodoc GET /api/test/route10 */
            type TestResponseInterface = [0|1, string]
            ',
        );
    }

    #[Test]
    public function controllerMethodWithIntersectionType(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route16 */
            type TypeWithExistingName = number
            ',
            expected: '
            /** @autodoc GET /api/test/route16 */
            type TypeWithExistingName = {
                created_at: string
            }
            ',
        );
    }

    #[Test]
    public function controllerMethodWithIntersectionAndUnionType(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route18 */
            ',
            expected: '
            /** @autodoc GET /api/test/route18 */
            type Route18Response = {
                id: number
                name: string
                uuid: {
                    x?: number
                }|string
            }
            ',
        );
    }

    #[Test]
    public function controllerMethodRequestBody(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route14 request */
            ',
            expected: '
            /** @autodoc GET /api/test/route14 request */
            type Route14Request = {
                data: Record<string, {
                    id: number
                    name?: string
                }>
            }
            ',
        );
    }

    #[Test]
    public function controllerMethodWithClassRepresentingAssocArray(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc GET /api/test/route29 */
            ',
            expected: '
            /** @autodoc GET /api/test/route29 */
            type Route29Response = Record<string, 1|2>
            ',
        );
    }

    #[Test]
    public function classRepresentingAssocArray(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /** @autodoc AutoDoc\Tests\TestProject\Entities\ClassThatRepresentsAssocArray */
            interface AssocArray = {}
            ',
            expected: '
            /** @autodoc AutoDoc\Tests\TestProject\Entities\ClassThatRepresentsAssocArray */
            type AssocArray = Record<string, unknown>
            ',
        );
    }

    #[Test]
    public function classRepresentingAssocArrayWithTemplateType(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\ClassThatRepresentsAssocArray<array{
             *     x: int,
             * }>
             */
            ',
            expected: '
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\ClassThatRepresentsAssocArray<array{
             *     x: int,
             * }>
             */
            type ClassThatRepresentsAssocArray = Record<string, {
                x: number
            }>
            ',
        );
    }

    #[Test]
    public function stringOrNull(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /**
             *
             * @autodoc string|null
             *
             */
            ',
            expected: '
            /**
             *
             * @autodoc string|null
             *
             */
            type UnnamedType = string|null
            ',
        );
    }

    #[Test]
    public function objectIntersection(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /**
             * @autodoc array{
             *     id: int,
             *     name?: string,
             * } & array{
             *     name: non-empty-string,
             *     uuid: string,
             * }
             *
             * Description...
             */
            type IntersectionExample = ?
            ',
            expected: '
            /**
             * @autodoc array{
             *     id: int,
             *     name?: string,
             * } & array{
             *     name: non-empty-string,
             *     uuid: string,
             * }
             *
             * Description...
             */
            type IntersectionExample = {
                id: number
                name: string
                uuid: string
            }
            ',
        );
    }

    #[Test]
    public function classWithOptions(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc AutoDoc\Tests\TestProject\Entities\Rocket {omit: 'id'} */
            EOS,
            expected: <<<EOS
            /** @autodoc AutoDoc\Tests\TestProject\Entities\Rocket {omit: 'id'} */
            type Rocket = {
                name: string
                category: 'Big'|'Small'
                launch_date: string|null
                is_flying: boolean
            }
            EOS,
        );
    }

    #[Test]
    public function boolWithBracesInComment(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc false */
            type BoolType = false // { x
            type IntType = 1|2|3
            EOS,
            expected: <<<EOS
            /** @autodoc false */
            type BoolType = false
            type IntType = 1|2|3
            EOS,
        );
    }

    #[Test]
    public function booleanResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc GET /api/test/route33 */
            export type BoolResponse = false

            const otherBool = true

            if (otherBool) {
                //
            }

            test

            EOS,
            expected: <<<EOS
            /** @autodoc GET /api/test/route33 */
            export type BoolResponse = true

            const otherBool = true

            if (otherBool) {
                //
            }

            test

            EOS,
        );
    }

    #[Test]
    public function assocArrayUnion(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc array{a: true} | array{b: false} */
            type UnnamedType = {
                a: true
            }|{
                b: false
            }

            EOS,
            expected: <<<EOS
            /** @autodoc array{a: true} | array{b: false} */
            type UnnamedType = {
                a: true
            }|{
                b: false
            }

            EOS,
        );
    }

    #[Test]
    public function omitKeysFromResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc GET /api/test/route18 {
             *     omit: 'id' | 'uuid'
             * }
             */
            test
            EOS,
            expected: <<<EOS
            /**
             * @autodoc GET /api/test/route18 {
             *     omit: 'id' | 'uuid'
             * }
             */
            type Route18Response = {
                name: string
            }
            test
            EOS,
        );
    }

    #[Test]
    public function genericClassWithGenericType(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc    AutoDoc\Tests\TestProject\Entities\GenericSubClass<15>   {
             *     omit: 'data'
             * }
             */

            const test = 1;
            EOS,
            expected: <<<EOS
            /**
             * @autodoc    AutoDoc\Tests\TestProject\Entities\GenericSubClass<15>   {
             *     omit: 'data'
             * }
             */
            type GenericSubClass = {
                n: number
            }

            const test = 1;
            EOS,
        );
    }

    #[Test]
    public function separateFileMode(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
             *     mode: 'separate_file',
             * }
             */
            EOS,
            expected: <<<EOS
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
             *     mode: 'separate_file',
             * }
             */
            type SimpleClass = import('@/types.ts').SimpleClass
            EOS,
        );
    }

    #[Test]
    public function separateFileModeWithIndent(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
                /**
                 * @autodoc AutoDoc\OpenApi\ExampleObject {
                 *     mode: 'separate_file',
                 * }
                 */
                type ExampleObject = {}
            EOS,
            expected: <<<EOS
                /**
                 * @autodoc AutoDoc\OpenApi\ExampleObject {
                 *     mode: 'separate_file',
                 * }
                 */
                type ExampleObject = import('@/types.ts').ExampleObject
            EOS,
        );
    }

    #[Test]
    public function separateFileModeWithOptionsAsAndWith(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
             *     mode: 'separate_file',
             *     as: 'AnotherName',
             *     with: object{ yo: string, state: AutoDoc\Tests\TestProject\Entities\StateEnum },
             * }
             */
            EOS,
            expected: <<<EOS
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
             *     mode: 'separate_file',
             *     as: 'AnotherName',
             *     with: object{ yo: string, state: AutoDoc\Tests\TestProject\Entities\StateEnum },
             * }
             */
            type SimpleClass = import('@/types.ts').AnotherName
            EOS,
        );
    }

    #[Test]
    public function separateFileModeResponse(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc GET /api/test/route32 {mode: 'separate_file'} */
            test
            EOS,
            expected: <<<EOS
            /** @autodoc GET /api/test/route32 {mode: 'separate_file'} */
            type Route32Response = import('@/types.ts').Route32Response
            test
            EOS,
        );
    }

    #[Test]
    public function separateFileModeResponseAs(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
              /** @autodoc GET /api/test/route36 {
               *     mode: 'separate_file', as: 'Route36Response' } */
              type Response = {}
              type AnotherType = {}
            EOS,
            expected: <<<EOS
              /** @autodoc GET /api/test/route36 {
               *     mode: 'separate_file', as: 'Route36Response' } */
              type Response = import('@/types.ts').Route36Response
              type AnotherType = {}
            EOS,
        );
    }

    #[Test]
    public function separateFileModeWithSameClass(): void
    {
        try {
            $this->assertTypeScriptGeneratedCorrectly(
                input: <<<EOS
                /**
                 * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
                 *     mode: 'separate_file',
                 * }
                 */
                EOS,
                expected: <<<EOS
                /**
                 * @autodoc AutoDoc\Tests\TestProject\Entities\SimpleClass {
                 *     mode: 'separate_file',
                 * }
                 */
                type SimpleClass = import('@/types.ts').SimpleClass
                EOS,
            );

        } catch (Exception $exception) {
            $this->assertStringContainsString('Type "SimpleClass" is already exported in file', $exception->getMessage());
        }
    }

    #[Test]
    public function phpstanTypeAlias(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc TestTypeAlias {
             *     from: AutoDoc\Tests\TestProject\Entities\ClassWithTypeAliasDefinition,
             * }
             */
            EOS,
            expected: <<<EOS
            /**
             * @autodoc TestTypeAlias {
             *     from: AutoDoc\Tests\TestProject\Entities\ClassWithTypeAliasDefinition,
             * }
             */
            type TestTypeAlias = {
                a: number
                b: string
            }
            EOS,
        );
    }

    #[Test]
    public function separateFileModeWithPhpstanTypeAlias(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc TestTypeAlias {
             *     from: 'AutoDoc\Tests\TestProject\Entities\ClassWithTypeAliasDefinition',
             *     mode: 'separate_file',
             * }
             */
            interface SomeType {
                a: number
            }
            EOS,
            expected: <<<EOS
            /**
             * @autodoc TestTypeAlias {
             *     from: 'AutoDoc\Tests\TestProject\Entities\ClassWithTypeAliasDefinition',
             *     mode: 'separate_file',
             * }
             */
            type SomeType = import('@/types.ts').SomeType
            EOS,
        );
    }

    #[Test]
    public function importedPhpstanTypeAlias(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: '
            /**
             * @autodoc TestTypeAlias {
             *     from: "AutoDoc\Tests\TestProject\Traits\TestTrait",
             * }
             */
            ',
            expected: '
            /**
             * @autodoc TestTypeAlias {
             *     from: "AutoDoc\Tests\TestProject\Traits\TestTrait",
             * }
             */
            type TestTypeAlias = {
                a: number
                b: string
            }
            ',
        );
    }

    #[Test]
    public function separateFileModeWithEnum(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: "
            /**
             * @autodoc RocketCategory {
             *     from: AutoDoc\Tests\TestProject\Entities\Rocket,
             *     mode: 'separate_file',
             * }
             */
            ",
            expected: "
            /**
             * @autodoc RocketCategory {
             *     from: AutoDoc\Tests\TestProject\Entities\Rocket,
             *     mode: 'separate_file',
             * }
             */
            type RocketCategory = import('@/types.ts').RocketCategory
            ",
        );
    }

    #[Test]
    public function responseWithExtraData(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc GET /api/test/route26 {
             *     with: array{
             *         token: string,
             *         hidden: true
             *     },
             *     omit: 'hidden',
             * }
             */
            function () {
            }
            EOS,
            expected: <<<EOS
            /**
             * @autodoc GET /api/test/route26 {
             *     with: array{
             *         token: string,
             *         hidden: true
             *     },
             *     omit: 'hidden',
             * }
             */
            type Route26Response = {
                number: 42.1
                token: string
            }
            function () {
            }
            EOS,
        );
    }

    #[Test]
    public function responseWithExtraClass(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /**
             * @autodoc GET /api/test/route30 {
             *     with: AutoDoc\Tests\TestProject\Entities\GenericClass<object{ name: ?string }>,
             *     omit: 'a',
             * }
             */
            interface X ...
            function () {
                /**
                 * @autodoc GET /api/test/route30 { omit: 'c'|'d' }
                 */
                /**
                 * @autodoc GET /api/test/route30 { only: 'd' }
                 */
            }
            EOS,
            expected: <<<EOS
            /**
             * @autodoc GET /api/test/route30 {
             *     with: AutoDoc\Tests\TestProject\Entities\GenericClass<object{ name: ?string }>,
             *     omit: 'a',
             * }
             */
            type X = {
                b: 2
                c: 100
                data: {
                    name: string|null
                }
            }|{
                b: 2
                d: 100
                data: {
                    name: string|null
                }
            }
            function () {
                /**
                 * @autodoc GET /api/test/route30 { omit: 'c'|'d' }
                 */
                type Route30Response = {
                    a: 1
                    b: 2
                }
                /**
                 * @autodoc GET /api/test/route30 { only: 'd' }
                 */
                type Route30Response = {}|{
                    d: 100
                }
            }
            EOS,
        );
    }

    #[Test]
    public function separateFileModeWithModifiedRequestBody(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: <<<EOS
            /** @autodoc GET /api/test/route14 request {
             *     mode: 'separate_file',
             *     with: array{
             *         token: string,
             *     },
             *  } */

            EOS,
            expected: <<<EOS
            /** @autodoc GET /api/test/route14 request {
             *     mode: 'separate_file',
             *     with: array{
             *         token: string,
             *     },
             *  } */
            type Route14Request = import('@/types.ts').Route14Request

            EOS,
        );
    }

    #[Test]
    public function enumWithOmit(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: "
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\RocketCategory {
             *     omit: 'Small',
             * }
             */
            ",
            expected: "
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\RocketCategory {
             *     omit: 'Small',
             * }
             */
            enum RocketCategory {
                Big = 'Big',
            }
            ",
        );
    }

    #[Test]
    public function enumWithOnly(): void
    {
        $this->assertTypeScriptGeneratedCorrectly(
            input: "
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\StateEnum {
             *     only: 'One',
             * }
             */
            ",
            expected: "
            /**
             * @autodoc AutoDoc\Tests\TestProject\Entities\StateEnum {
             *     only: 'One',
             * }
             */
            enum StateEnum {
                One = 1,
            }
            ",
        );
    }
}
